name: Correr Pruebas
env:
  DOTNET_VERSION: '8.x'
  SONAR_ORG: 'ximena-ortiz'
  SONAR_PROJECT: 'ximena-ortiz_sustainpartners'
  SONAR_HOST_URL: 'https://sonarcloud.io'
  SONAR_TOKEN: '62261b0d74dc4a098baaae76a6b239f4a1900c64'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Configurar Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Crear .env
        run: |
          echo "DATABASE_URL=jdbc:postgresql://ep-small-haze-88087949.us-east-2.aws.neon.tech/dbSustainPartners" > .env
          echo "DATABASE_USER=ximena-ortiz" >> .env
          echo "DATABASE_PASSWORD=neq9Gm5awICO" >> .env
          echo "RECAPTCH_PRIVATE_KEY=6LfVXgspAAAAAFOIm5PqiXZqbtYibfKzGNDlUOCx" >> .env

      - name: Instalar Dependencias y correr Tests
        run: mvn clean test jacoco:report

      - name: Subir Reporte de Cobertura
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests-report
          path: target/site/jacoco

      - name: Subir Reporte de Tests
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-tests-report
          path: target/cucumber-reports.html

      - name: SonarQube Scan
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=${{ env.SONAR_PROJECT }} \
            -Dsonar.organization=${{ env.SONAR_ORG }} \
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }} \
            -Dsonar.login=${{ env.SONAR_TOKEN }} \
            -Dsonar.exclusions=src/main/java/com/loscuchurrumines/controller/**

            